### ISSUE TITLE
NFT selection missing?

### ISSUE THREAD

**Issue by Legitti** [LilithRainbows/HabboCustomFlashAIR#13]
They recently added the NFT Menu to AIR as well, but I can't find it here after the last update?

Is it possible to add this?

**Comment by LilithRainbows** [comment]
Because the base of the custom client is an old swf, but i will update it someday :)

**Comment by Legitti** [comment]
Hey, since you removed the effect menu there is no way to use NFT and effect on the latest release.

Could you please update the flash version or re-enable the custom effects menu?

**Comment by Legitti** [comment]
Are you still updating this? Habbo just got updated so wondering if it broke anything
